version: '3'
networks:
  chat-network:  # Define a network
  
services:
  eureka-server:
    build:
      context: /chat-app-service-discovery
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - chat-network  # Attach this service to chat-network

  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/upstream.conf:/etc/nginx/upstream.conf
      - ./nginx/update_nginx.sh:/update_nginx.sh
    depends_on:
      - eureka-server
    networks:
      - chat-network  # Attach this service to chat-network
    entrypoint: ["sh", "-c", "while true; do /update_nginx.sh; sleep 30; done"]